package pl.project13.protoscala.utils

import com.google.protobuf.DescriptorProtos
import java.lang._

/**
 * Date: 3/28/11
 *
 * @author Konrad Malawski
 */
class CommentsGenerator {

  val initialComment: String = "// Generated by the protocol buffer compiler.  DO NOT EDIT!\n" +
                               "// source: %s\n"

  def initialComment(sourceStringBuilder: StringBuilder, protoFile: DescriptorProtos.FileDescriptorProtoOrBuilder): Unit = {
    val name = protoFile.getName
    sourceStringBuilder.append(initialComment.format(name))
  }
}