package pl.project13.protoscala.utils

import com.google.protobuf.DescriptorProtos
import java.lang._

/**
 * Date: 3/28/11
 *
 * @author Konrad Malawski
 */
class CommentsGenerator {

  val initialComments = List("Generated by the protocol buffer compiler.  DO NOT EDIT!\n",
                             "source: %s\n")

  def initialComment(sourceStringBuilder: SourceStringBuilder, protoFile: DescriptorProtos.FileDescriptorProtoOrBuilder): Unit = {
    val name = protoFile.getName

    for (initialComment <- initialComments) {
      sourceStringBuilder.appendComment(initialComment.format(name))
    }
    sourceStringBuilder.appendNewLine
  }
}